- name: Add specified repository
  apt_repository:
    repo: ppa:longsleep/golang-backports

- name: Run apt update
  apt:
    update_cache: yes

- name: Install golang
  apt:
    name: golang-go
    state: latest
