- hosts: raspberrypi-ubuntu
  become: yes
  roles:
    - common
    - golang
    - docker
    - node-exporter
    - i2c-tools
    - name: newrelic.newrelic-infra
      vars:
        nrinfragent_config:
          license_key: "{{ LICENCE }}"
